# Generated by Django 5.1.4 on 2025-02-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialcourse",
            name="file",
        ),
        migrations.AddField(
            model_name="materialcourse",
            name="file_path",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
