# Generated by Django 5.1.4 on 2025-02-22 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_materialcourse_file_materialcourse_file_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="course",
            new_name="course_id",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("user_id", "course_id")},
        ),
    ]
