# Generated by Django 5.1.4 on 2025-02-22 15:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_rename_course_student_course_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="course_id",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("user", "course")},
        ),
    ]
