# Generated by Django 5.1.4 on 2025-02-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_rename_course_id_student_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="coursefeedback",
            name="course",
        ),
        migrations.RemoveField(
            model_name="coursefeedback",
            name="student",
        ),
        migrations.RemoveField(
            model_name="forum",
            name="course",
        ),
        migrations.RemoveField(
            model_name="post",
            name="forum",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="student",
        ),
        migrations.RemoveField(
            model_name="materialcourse",
            name="course",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.DeleteModel(
            name="CourseFeedback",
        ),
        migrations.DeleteModel(
            name="Forum",
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
        migrations.DeleteModel(
            name="MaterialCourse",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
